apiVersion: v1
kind: Secret
metadata:
  name: "airflow-secrets"
type: Opaque
data:
  r3d5un-password: YWRtaW4=
  # The `webserver-key` and `fernet-key` valyes must be created using the
  # following command:
  # `python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" | base64`
  airflow-webserver-key: Q1pCd19MWHBDWUN1YnJKMzFIOGRJMjRfV3lJZmQ3RXo3SkMzZW1nUWI5VT0K
  airflow-fernet-key: VUFncVk4M3Yza3BST3k5NFdZODhyQ2h1ZVdTNy1TaTVDN3VNbWJ1c0lsVT0K
